-- MySQL Script generated by MySQL Workbench
-- Tue Jul  5 12:01:29 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema forum-db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema forum-db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `forum-db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `forum-db` ;

-- -----------------------------------------------------
-- Table `forum-db`.`topic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forum-db`.`topic` (
  `TopicID` INT NOT NULL,
  `CreationDate` DATETIME NOT NULL,
  `ModifDate` DATETIME DEFAULT NULL,
  `TopicTitle` VARCHAR(50) NOT NULL,
`CreatedBy`TEXT NOT NULL,
  PRIMARY KEY (`TopicID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `forum-db`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forum-db`.`comment` (
  `CommentID` INT NOT NULL,
  `CreationDate` DATETIME NOT NULL,
  `ModifDate` DATETIME DEFAULT NULL,
  `Content` TEXT NOT NULL,
`CreatedBy`TEXT NOT NULL,
`CommentTopicId` INT NOT NULL,
  PRIMARY KEY (`CommentID`),
  CONSTRAINT `CommentTopic_TopicID`
    FOREIGN KEY (`CommentTopicId`)
    REFERENCES `forum-db`.`topic` (`TopicID`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;